<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>syncdirs</AssemblyName>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SyncDirs.Tests" />
  </ItemGroup>
  
</Project>
